### ISSUE TITLE
Empty directories not properly extracted

### ISSUE THREAD

**Issue by pulkomandy** [jca02266/lha#17]
Test file: http://ace.cpcscene.net/_media/ace-morphos-1.14.lha

This file is created on MorphOS with the -e option to Amiga version of lha (to include empty directories). When extracting with this version of lha, I get empty files instead of empty directories for Discs, Grabs, Logs, ROMs, Share, Snapshots, and Tapes directories.

**Comment by jca02266** [comment]
Normaly, lha header structure for just a header is below

> 00  2: 53(0x0035)
> 02  5: "-lhd-"
> 07  4: 0(0x00000000)
> 11  4: 0(0x00000000)
> 15  4: 1607757798(0x5fd46fe6)
> 19  1: 32(0x20) ' '
> 20  1: 2(0x02)
> 21  2: 0(0x0000)
> 23  1: 85(0x55) 'U'
> 24  2: 5(0x0005)
-snip-
> bar/
> drwxr-xr-x   501/20          0       0 ****** -lhd- 0000 2020-12-12 16:23:18 [2]

But it was below

> 00  2: 44(0x002c)
> 02  5: "-lh0-"
> 07  4: 0(0x00000000)
> 11  4: 0(0x00000000)
> 15  4: 1489089380(0x58c1b364)
> 19  1: 0(0x00)
> 20  1: 2(0x02)
> 21  2: 0(0x0000)
> 23  1: 65(0x41) 'A'
> 24  2: 13(0x000d)
-snip-
> ACE/Discs/
> [unknown]                    0       0 ****** -lh0- 0000 2017-03-10 04:56:20 [2]

The method part of this header (offset 02) was "-lh0-" instead of "-lhd-" (directory)

**Comment by jca02266** [comment]
Fixed 959d248
