### ISSUE TITLE
utime() patch, version number

### ISSUE THREAD

**Issue by Rhialto** [jca02266/lha#20]
Hi! I am packaging `lha` for pkgsrc (see http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/archivers/lha ). I have a lot of Amiga `.lha` files around so `lha` is very useful to me.

The previous distribution file from http://www2m.biglobe.ne.jp/~dolphin/lha/lha-unix.htm is no longer available, so I found your version.

You have integrated almost all patches that `pkgsrc` had for `lha-1.14i`. There is one patch that might be good to have upstream. It replaces a call to `utime()` with `utimes()`, because `utime()` is listed as deprecated.

```
--- src/lhext.c.orig    2020-12-17 15:59:30.545844796 +0000
+++ src/lhext.c
@@ -220,13 +220,15 @@ adjust_info(name, hdr)
     char           *name;
     LzHeader       *hdr;
 {
-    struct utimbuf utimebuf;
+    struct timeval utimebuf[2];
 
     /* adjust file stamp */
-    utimebuf.actime = utimebuf.modtime = hdr->unix_last_modified_stamp;
+    utimebuf[0].tv_sec = hdr->unix_last_modified_stamp;
+    utimebuf[0].tv_usec = 0;
+    utimebuf[1] = utimebuf[0];
 
     if ((hdr->unix_mode & UNIX_FILE_TYPEMASK) != UNIX_FILE_SYMLINK)
-        utime(name, &utimebuf);
+        utimes(name, &utimebuf[0]);
 
     if (hdr->extend_type == EXTEND_UNIX
         || hdr->extend_type == EXTEND_OS68K
```
(packaging patches are usually not the best practice, but short and minimal; I noticed that there is some code to conditionally define `struct utimbuf`, which could be removed as well).

Further, I could no so easily find the version number. I had to look at `configure.ac` to find `1.14i-ac20081023`.  2008-10-23 is a long time ago :-) When it is an appropriate moment, can you maybe create a release version, with a new version number (maybe `1.15`)? That, with a nice tag, so that it appears in https://github.com/jca02266/lha/releases would be very nice.

Thanks for keeping lha updated!

**Comment by jca02266** [comment]
I'm applied your patch and changed a little.  72111ee
Thanks for your suggestion!

I'm not going to make a release file, because I don't think it needs to be advertised.
I don't think LHA is a software that will be widely interesting.
But, I bumped timestamp in today: 50937c3

**Comment by Rhialto** [comment]
Thanks!
