### ISSUE TITLE
Corrupting old Amiga archives

### ISSUE THREAD

**Issue by wmcbrine** [jca02266/lha#24]
I have a couple of old files from an Amiga, from 1994 and 1997 respectively, which get corrupted when I try to update them with LHa for Unix. They work OK with LHA 2.13 in DOS.

The files are sample Blue Wave packets that were included with two different versions of AmyBW, a Blue Wave reader for the Amiga. I have them in my collection of test packets for use with MultiMail, mainly to test LHA support. (Most offline reader packets are Zip files.) Initially, they extract OK, but when MultiMail tries to update the read marker file, LHa fails. I get slightly different errors with each packet, but I get them consistently across systems -- so far, I've only tried on a Raspberry Pi running 32-bit Raspbian (armv7l), and an M1 Mac running Big Sur (arm64). Here's what the output of LHa looks like:

demopkt.001
===========

Initial extraction
------------------

DEMOPKT.DAT     - Melted   :  oo
DEMOPKT.FTI     - Melted   :  o
DEMOPKT.INF     - Melted   :  o
DEMOPKT.MIX     - Melted   :  o
DEMOPKT.XTI     - Melted   :  o
NEWFILES.BW     - Melted   :  o
READER1.NWS     - Melted   :  o

Attempting to update the .xti
-----------------------------

LHa: Error: Unknown level header (level 28)
DEMOPKT.xti     - Frozen(40%) o

Second extraction
-----------------

DEMOPKT.DAT     - Melted   :  oo
LHa: Error: CRC error: "DEMOPKT.DAT"
LHa: Error: Unknown level header (level 80)

demopkt.002
===========

Initial extraction
------------------

DEMOPKT.DAT     - Melted   :  oooooooooooo
DEMOPKT.FTI     - Melted   :  oo
DEMOPKT.INF     - Melted   :  o
DEMOPKT.MIX     - Melted   :  o
NEWFILES.XB     - Melted   :  o
READER1.NWS     - Melted   :  o

Attempting to update the .xti
-----------------------------

LHa: Error: Unknown level header (level 35)
DEMOPKT.xti     - Frozen(13%) o

Second extraction
-----------------

DEMOPKT.DAT     - Melted   :  oooooooooooo
LHa: Error: CRC error: "DEMOPKT.DAT"
LHa: Error: Unknown level header (level 58)

[packets.zip](https://github.com/jca02266/lha/files/7203772/packets.zip)

**Comment by jca02266** [comment]
Can you try the #25 ?

**Comment by wmcbrine** [comment]
Fix is good

**Comment by jca02266** [comment]
Thanks!
