### ISSUE TITLE
Request: Extract single / several file(s)

### ISSUE THREAD

**Issue by tednilsen** [jca02266/lha#28]
Thank you for this.
...would be nice to have to option to extract 1 (or more) files. Say I have a large file-list of lha archives, and inside each of these there is a *.readme file I wanne extract (and process / read).
I have 1000 lha files I open and process one file in the archive:

`
pi@raspberrypi:~/src/src-code/test $ ls -l
total 8408
-rw-r--r-- 1 pi pi 1835853 Feb  5 22:31 A10TankKiller_v2.0_3Disk.lha
-rw-r--r-- 1 pi pi 2975982 Feb  5 22:33 AbandonedPlaces2_v2.0.lha
-rw-r--r-- 1 pi pi 3789038 Feb  5 22:32 AbandonedPlaces_v1.3_1000.lha
pi@raspberrypi:~/src/src-code/test $ lha -l A10TankKiller_v2.0_3Disk.lha
PERMISSION  UID  GID      SIZE  RATIO     STAMP           NAME
---------- ----------- ------- ------ ------------ --------------------
[unknown]                  900  48.7% Jul  6  2012 A10TankKiller3Disk.info
[unknown]                 8098  61.7% Jul  6  2012 A10TankKiller3Disk/A10TankKiller3Disk.info
[unknown]                 3656  73.4% Oct  6  2002 A10TankKiller3Disk/A10TankKiller3Disk.Slave
[unknown]                10380  60.8% Jul  6  2012 A10TankKiller3Disk/data/A10
[unknown]                82756  78.6% Mar 18  1992 A10TankKiller3Disk/data/A10.sfx
[unknown]                 5562  28.1% Mar 18  1992 A10TankKiller3Disk/data/A10_20.icon
[unknown]                 8008  48.3% Mar 18  1992 A10TankKiller3Disk/data/AmigaSnd.drv
[unknown]                 1964  62.7% Mar 18  1992 A10TankKiller3Disk/data/c/avail
[unknown]                11284  54.8% Mar 18  1992 A10TankKiller3Disk/data/c/More
[unknown]                 2568  61.1% Mar 18  1992 A10TankKiller3Disk/data/c/run
[unknown]               233380  85.2% Mar 18  1992 A10TankKiller3Disk/data/Cmp1.001
[unknown]                  229 100.0% Mar 18  1992 A10TankKiller3Disk/data/Cmp1.RMF
[unknown]               223108  84.5% Mar 18  1992 A10TankKiller3Disk/data/Cmp2.001
[unknown]                  229 100.0% Mar 18  1992 A10TankKiller3Disk/data/Cmp2.RMF
[unknown]               144919  86.8% Mar 18  1992 A10TankKiller3Disk/data/Cmp3.001
[unknown]                  189 100.0% Mar 18  1992 A10TankKiller3Disk/data/Cmp3.RMF
[unknown]                   16 100.0% Mar 18  1992 A10TankKiller3Disk/data/control.prf
[unknown]                  232  51.7% Mar 18  1992 A10TankKiller3Disk/data/devs/system-configuration
[unknown]                  900  37.8% Mar 18  1992 A10TankKiller3Disk/data/Drawer.icon
[unknown]                  628  43.0% Mar 18  1992 A10TankKiller3Disk/data/Drawer20.icon
[unknown]                30548  94.8% Mar 18  1992 A10TankKiller3Disk/data/Install
[unknown]                   92  80.4% Mar 18  1992 A10TankKiller3Disk/data/MName1.Dat
[unknown]                   95  78.9% Mar 18  1992 A10TankKiller3Disk/data/MName2.Dat
[unknown]                   92  77.2% Mar 18  1992 A10TankKiller3Disk/data/MName3.Dat
[unknown]               167496  52.1% Jul  6  2012 A10TankKiller3Disk/data/PS
[unknown]                 1657  52.6% Mar 18  1992 A10TankKiller3Disk/data/ReadMe
[unknown]               235808  54.4% Jul  6  2012 A10TankKiller3Disk/data/Sim
[unknown]                    5 100.0% Mar 18  1992 A10TankKiller3Disk/data/Vol1.Map
[unknown]                    5 100.0% Mar 18  1992 A10TankKiller3Disk/data/Vol2.Map
[unknown]                    5 100.0% Mar 18  1992 A10TankKiller3Disk/data/Vol3.Map
[unknown]               396448  80.8% Mar 18  1992 A10TankKiller3Disk/data/Volume.001
[unknown]               517925  86.3% Mar 18  1992 A10TankKiller3Disk/data/Volume.002
[unknown]               199451  95.5% Mar 18  1992 A10TankKiller3Disk/data/Volume.003
[unknown]                  891  87.7% Mar 18  1992 A10TankKiller3Disk/data/Volume.RMF
[unknown]                47664  38.1% Oct 19  2001 A10TankKiller3Disk/Manual
[unknown]                 1396  63.0% Jul  6  2012 A10TankKiller3Disk/Manual.info
[unknown]                 2018  56.0% Oct  6  2002 A10TankKiller3Disk/ReadMe
[unknown]                 1396  63.2% Jul  6  2012 A10TankKiller3Disk/ReadMe.info
---------- ----------- ------- ------ ------------ --------------------
 Total        38 files 2341998  78.3% Feb  5 22:31
pi@raspberrypi:~/src/src-code/test $
`
I need to process each *.Slave files in each lha archive, like in this example the "A10TankKiller3Disk/A10TankKiller3Disk.Slave" file.

Hope you can implement it... Thanks!

**Comment by tednilsen** [comment]
`A10TankKiller3Disk/A10TankKiller3Disk.Slave`

**Comment by jca02266** [comment]
You can do it like below:

```
lha -l A10TankKiller_v2.0_3Disk.lha '*.Slave'
```

**Comment by tednilsen** [comment]
> You can do it like below:
> 
> ```
> lha -l A10TankKiller_v2.0_3Disk.lha '*.Slave'
> ```

Yes thank you, that will list the *.Slave files - Now I wanne EXTRACT only that file?

**Comment by jca02266** [comment]
You can do it the same way.

```
lha x A10TankKiller_v2.0_3Disk.lha '*.Slave'
```

**Comment by tednilsen** [comment]
> You can do it the same way.
> 
> ```
> lha x A10TankKiller_v2.0_3Disk.lha '*.Slave'
> ```

Ahhhh thank you! All works fine.
